namespace Config
{
	public enum PageID
	{
		Invalid = -1,
		HomePage = 1,
		SettingsPage = 2,
		ShopPage = 3,
		MiniEnterPage = 4,
		MiniExitPage = 5,
		MiniFailedPage = 6,
		MiniSucceedPage = 7,
		MiniShopPage = 8,
		MiniShopSinglePage = 9,
		AdsPropPopup = 10,
		SwapEnergyPage = 11,
		RewardPage = 12,
		ScrewGamePage = 13,
		Jam3DGamePage = 14,
		TileGamePage = 15,
		BusGamePage = 16,
		TripleGamePage = 17,
		GuidePage = 18,
		MiniGuidePage = 19,
		GamePage = 20,
		OverPage = 21,
		MiniMapPage = 22,
		MiniRulePage = 23,
		MiniGameOverPage = 24,
		MiniRevivePopup = 25,
		TowerMapPage = 26,
		TowerRulePage = 27,
		GMPage = 99,
	}
}