namespace Config
{
	public enum PageID
	{
		Invalid = -1,
		HomePage = 1,
		SettingsPage = 2,
		ShopPage = 3,
		DailyPage = 4,
		GamePage = 5,
		OverPage = 6,
		TutorialPage = 9,
		AdPropPopup = 10,
		AdsRestPopup = 11,
		RevivePopup = 12,
		GuidePage = 13,
		EventStartPopup = 14,
		EventAwardPopup = 15,
		EventTutorialPage = 16,
		EventOverPage = 17,
		EventChestPage = 18,
		EventPuzzlePage = 19,
		EventTangramPage = 20,
		TournamentPage = 21,
		TournamentTutorialPage = 22,
		TournamentOverPage = 23,
		NamelPopup = 24,
		MiniMapPage = 25,
		MiniRulePage = 26,
		MiniShopPage = 27,
		MiniShopSinglePage = 28,
		MiniGameOverPage = 29,
		RewardPage = 30,
		MiniRevivePopup = 31,
		AdsPropPopup = 32,
		TowerMapPage = 33,
		TowerRulePage = 34,
		MiniGuidePage = 35,
		ScrewGamePage = 36,
		Jam3DGamePage = 37,
		GMPage = 99,
	}
}