namespace Config
{
	public enum PageID
	{
		Invalid = -1,
		HomePage = 1,
		SettingsPage = 2,
		ShopPage = 3,
		MiniEnterPage = 4,
		DailyPage = 5,
		GamePage = 6,
		OverPage = 7,
		TutorialPage = 8,
		AdPropPopup = 9,
		AdsRestPopup = 10,
		RevivePopup = 11,
		GuidePage = 12,
		EventStartPopup = 13,
		EventAwardPopup = 14,
		EventTutorialPage = 15,
		EventOverPage = 16,
		EventChestPage = 17,
		EventPuzzlePage = 18,
		EventTangramPage = 19,
		TournamentPage = 20,
		TournamentTutorialPage = 21,
		TournamentOverPage = 22,
		NamelPopup = 23,
		MiniMapPage = 24,
		MiniRulePage = 25,
		MiniShopPage = 26,
		MiniShopSinglePage = 27,
		MiniGameOverPage = 28,
		RewardPage = 29,
		MiniRevivePopup = 30,
		AdsPropPopup = 31,
		TowerMapPage = 32,
		TowerRulePage = 33,
		MiniGuidePage = 34,
		ScrewGamePage = 35,
		Jam3DGamePage = 36,
		GMPage = 99,
	}
}