// GENERATED BY UNITY. REMOVE THIS COMMENT TO PREVENT OVERWRITING WHEN EXPORTING AGAIN
package com.nutz.game;

import android.content.Intent;
import android.os.Bundle;
import android.view.Window;
import android.widget.FrameLayout;
import android.view.ViewGroup;
import com.nutz.game.ad.Mediation;
import com.nutz.game.message.notify.SFNotificationUtil;
import com.unity3d.player.UnityPlayerActivity;
import android.widget.RelativeLayout; 


public class LaunchActivity extends UnityPlayerActivity
{
    // Setup activity layout
    @Override protected void onCreate(Bundle savedInstanceState)
    {
        requestWindowFeature(Window.FEATURE_NO_TITLE);
        super.onCreate(savedInstanceState);

        ViewGroup viewGroup = findViewById(android.R.id.content);
        RelativeLayout layout = new RelativeLayout(this);
        RelativeLayout.LayoutParams params = new RelativeLayout.LayoutParams(RelativeLayout.LayoutParams.MATCH_PARENT,
                ViewGroup.LayoutParams.MATCH_PARENT);
        layout.setLayoutParams(params);
        layout.setClickable(false);
        layout.setFocusable(false);
        viewGroup.addView(layout);

        Mediation.getInstance().init(this, layout);
        SFNotificationUtil.checkToSendNotification(this.getApplication());
    }

    // Quit Unity
    @Override protected void onDestroy ()
    {
        super.onDestroy();
        Mediation.getInstance().onDestroy();
    }

    // Pause Unity
    @Override protected void onPause()
    {
        super.onPause();
        Mediation.getInstance().onPause();
    }

    // Resume Unity
    @Override protected void onResume()
    {
        super.onResume();
        Mediation.getInstance().onResume();

        //修复 sdk 切后台回来黑屏的问题，
        //mUnityPlayer.postInvalidate();
    }

}
